version: "3"

services:
  database:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: loan
    ports:
      - "3306:3306"

  storage:
    image: minio/minio:RELEASE.2024-08-29T01-40-52Z.fips
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - loan-data:/data

volumes:
  loan-data:
